# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 18:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('priority', models.TextField()),
                ('status', models.TextField(blank=True, default='todo')),
                ('createTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('createUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createUser', to=settings.AUTH_USER_MODEL)),
                ('modificationUserID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificationUser', to=settings.AUTH_USER_MODEL)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.Projects')),
                ('solveUserID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solveUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
