# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
